name:                free-monads
version:             0.1.0.0
github:              "stoeffel/free-monads"
license:             BSD3
author:              "Christoph Hermann"
maintainer:          "schtoeffel@gmail.com"
copyright:           "2019 Christoph Hermann"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/stoeffel/free-monads#readme>

dependencies:
- base >= 4.7 && < 5
- protolude
- text

library:
  source-dirs: .

